"""
Title: Find the Difference

Problem:
You are given two strings `s` and `t`. String `t` is generated by shuffling string `s` and adding one extra character at a random position.
Write a function to find the extra character added to `t`.

Constraints:
- Both strings consist of lowercase English letters.
- The length of `t` is exactly one more than the length of `s`.
- The strings may contain duplicate letters.

Examples:
Input: s = "abcd", t = "abcde"
Output: "e"

Input: s = "aabbcc", t = "abcbacd"
Output: "d"

Input: s = "x", t = "xx"
Output: "x"

Test Cases:
1. find_the_difference("abcd", "abcde") should return "e"
2. find_the_difference("aabbcc", "abcbacd") should return "d"
3. find_the_difference("x", "xx") should return "x"
4. find_the_difference("hello", "helzlo") should return "z"
5. find_the_difference("aaa", "aaaa") should return "a"
"""

def find_the_difference(s: str, t: str) -> str:
    # TODO: Implement the function to find the extra character in t
    pass

# Test Cases
def test_find_the_difference():
    assert find_the_difference("abcd", "abcde") == "e"
    assert find_the_difference("aabbcc", "abcbacd") == "d"
    assert find_the_difference("x", "xx") == "x"
    assert find_the_difference("hello", "helzlo") == "z"
    assert find_the_difference("aaa", "aaaa") == "a"
    print("All test cases passed!")

# Run test cases
test_find_the_difference()
